'use strict';

// tests for startSimulation
// Generated by serverless-mocha-plugin

const mod = require('../handler.js');
const helpers = require('../helpers.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'startSimulation' });

describe('startSimulation', () => {
    before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

        done();
    });

    /*it('implement tests here', () => {
        return wrapped.run({}).then((response) => {
            expect(response).to.not.be.empty;
        });
    });*/
});
